services:
  - type: web
    name: recipe-ripper
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
databases: # this section provides some additional database configuration
  - name: db
    plan: free
    ipAllowList: []
